# Generated by Haxe 3.4.4
# coding: utf-8



class lib_HelloWorldLib:
    __slots__ = ()

    def __init__(self):
        pass

    @staticmethod
    def helloWorld():
        print("Hello World Library")

